"""hotel and external schema

Revision ID: 72e850f4fa7b
Revises: 
Create Date: 2026-09-25 14:48:50.165775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e850f4fa7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('stay_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_sold_out', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_arrivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport', sa.String(length=10), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('flight_count', sa.Integer(), nullable=True),
    sa.Column('avg_fare_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=True),
    sa.Column('temp_min_c', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=60), nullable=True),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('stay_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rooms_available', sa.Integer(), nullable=False),
    sa.Column('rooms_sold', sa.Integer(), nullable=False),
    sa.Column('room_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_type_id', 'stay_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_performance')
    op.drop_table('room_types')
    op.drop_table('weather')
    op.drop_table('hotels')
    op.drop_table('flight_arrivals')
    op.drop_table('events')
    op.drop_table('competitor_rates')
    # ### end Alembic commands ###
